#!/usr/bin/env python
# -*- coding: utf-8 -*-
##########################################################################
# ./getconfig - Retrieves configuration file from a netgear switch
# Copyright © 2014 Ghislain Loaec <gloaec@cadoles.com>
#
# License GPLv3: http://sourceforge.net/directory/license:gplv3/
##########################################################################

import sys
import os
import argparse
from netgear import Api

config = {}

def main(argv):
    version = ' '.join([sys.argv[0], config['VERSION']])
    parser  = argparse.ArgumentParser()

    parser.add_argument("-o", "--outputfile", 
                help    = "Destination file")
    parser.add_argument("-D", "--debug", 
                action  = "store_true",
                help    = "Debug mode")
    parser.add_argument("-v", "--version", 
                action  = 'version', 
                version = version,
                help    = "Display version")

    args = parser.parse_args()

    api = Api(app_host     = config['APP_HOST'], 
              app_password = config['APP_PASSWORD'], 
              debug        = args.debug)

    try:
        res = api.downloadConfig()
        if args.outputfile is None:
            print res, "\n"
        else:
            f = open(args.outputfile, 'w')
            f.write(res)
            f.close()
    except Exception, e:
        print "Error:", e

if __name__ == "__main__":
    execfile(os.path.join(os.path.dirname(os.path.realpath(__file__)), "netgear.conf"), config)
    main(sys.argv[1:])
